# Common以下のコード補足

In [1]:
import numpy as np

***
# functions

## softmax関数
xが1次元，2次元の場合に分けて，オーバーフロー対策のために各データから最大値を引く

In [2]:
x = np.random.rand(3, 10)
print(x)
print(x.max(axis=1, keepdims=True))
print(x - x.max(axis=1, keepdims=True))

[[0.60075025 0.33271303 0.17343785 0.13577377 0.46292412 0.09548429
  0.01352433 0.96772625 0.69869944 0.72463471]
 [0.34792022 0.16759107 0.10325365 0.98483311 0.77144506 0.33943378
  0.30998707 0.14994264 0.5835499  0.43993297]
 [0.94991387 0.10350156 0.72904534 0.90166407 0.55088631 0.35083577
  0.13604599 0.04418678 0.35565199 0.82587936]]
[[0.96772625]
 [0.98483311]
 [0.94991387]]
[[-0.366976   -0.63501322 -0.79428841 -0.83195248 -0.50480213 -0.87224197
  -0.95420192  0.         -0.26902681 -0.24309155]
 [-0.63691289 -0.81724204 -0.88157946  0.         -0.21338804 -0.64539933
  -0.67484604 -0.83489047 -0.4012832  -0.54490014]
 [ 0.         -0.84641231 -0.22086852 -0.04824979 -0.39902755 -0.5990781
  -0.81386787 -0.90572708 -0.59426188 -0.1240345 ]]


## cross_entropy_error
- 1データ分
$$
L = - \Sigma_k t_k \log y_k
$$

- バッチ
$$
L = - \frac{1}{N} \Sigma_n \Sigma_k t_{nk} \log y_{nk}
$$

- targetラベルがone-hot-vectorであれば，正解ラベルに対応するlog yを計算するだけ．

***
# layers

## SigmoidWithLoss
$$
L = - \{ t \log y + (1 - t) \log(1 - y) \}
$$

- CBOWモデルの高速化(多値分類を二値分類に置き換える)で使用．
- 答えが不正解のときt = 0, 正解のときt = 1が渡される．

In [14]:
y = np.arange(5).reshape(5, 1)
# 以下の配列と t = 0 or 1 のラベルをcross_entropy_errorに渡せばよい
print(y)
print(np.c_[1 - y, y])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 1  0]
 [ 0  1]
 [-1  2]
 [-2  3]
 [-3  4]]
