# Common以下のコード補足

In [1]:
import numpy as np

***
# functions

## softmax関数
xが1次元，2次元の場合に分けて，オーバーフロー対策のために各データから最大値を引く

In [2]:
x = np.random.rand(3, 10)
print(x)
print(x.max(axis=1, keepdims=True))
print(x - x.max(axis=1, keepdims=True))

[[0.60075025 0.33271303 0.17343785 0.13577377 0.46292412 0.09548429
  0.01352433 0.96772625 0.69869944 0.72463471]
 [0.34792022 0.16759107 0.10325365 0.98483311 0.77144506 0.33943378
  0.30998707 0.14994264 0.5835499  0.43993297]
 [0.94991387 0.10350156 0.72904534 0.90166407 0.55088631 0.35083577
  0.13604599 0.04418678 0.35565199 0.82587936]]
[[0.96772625]
 [0.98483311]
 [0.94991387]]
[[-0.366976   -0.63501322 -0.79428841 -0.83195248 -0.50480213 -0.87224197
  -0.95420192  0.         -0.26902681 -0.24309155]
 [-0.63691289 -0.81724204 -0.88157946  0.         -0.21338804 -0.64539933
  -0.67484604 -0.83489047 -0.4012832  -0.54490014]
 [ 0.         -0.84641231 -0.22086852 -0.04824979 -0.39902755 -0.5990781
  -0.81386787 -0.90572708 -0.59426188 -0.1240345 ]]


## cross_entropy_error
- 1データ分
$$
L = - \Sigma_k t_k \log y_k
$$

- バッチ
$$
L = - \frac{1}{N} \Sigma_n \Sigma_k t_{nk} \log y_{nk}
$$

- targetラベルがone-hot-vectorであれば，正解ラベルに対応するlog yを計算するだけ．

In [17]:
# 教師データのone-hot-vectorを正解ラベルのインデックスに変換
t = np.array([[0, 0, 1, 0],
              [1, 0, 0, 0],
              [0, 0, 0, 1]])
t.argmax(axis=1)

array([2, 0, 3])

***
# layers

## SigmoidWithLoss
$$
y = \frac{1}{1 + \exp(-x)}
\\ \\
L = - \{ t \log y + (1 - t) \log(1 - y) \}
$$
- CBOWモデルの高速化(多値分類を二値分類に置き換える)で使用．
- 答えが不正解のときt = 0, 正解のときt = 1が渡される．

In [21]:
y = np.random.rand(5).reshape(5, 1)
# 以下の配列と t = 0 or 1 のラベルをcross_entropy_errorに渡せばよい
print(y)
print(np.c_[1 - y, y])

[[0.59855412]
 [0.6860394 ]
 [0.01790132]
 [0.59828537]
 [0.30156778]]
[[0.40144588 0.59855412]
 [0.3139606  0.6860394 ]
 [0.98209868 0.01790132]
 [0.40171463 0.59828537]
 [0.69843222 0.30156778]]


***
# trainer
## Trainer

In [28]:
x = np.random.randn(1000)
data_size = len(x)
batch_size = 32
max_iters = data_size // batch_size
max_epoch = 10
eval_interval = 20

In [33]:
# データのシャッフル
np.random.permutation(10)

array([9, 2, 4, 1, 5, 0, 7, 8, 6, 3])

In [31]:
for epoch in range(max_epoch):
    print(f'-----------epoch: {epoch}-----------')
    print('ここでデータをシャッフル')
    
    for iters in range(max_iters):
        print(f'iters: {iters}')
        print('ミニバッチを取得')
        print('順伝播で損失計算')
        print('逆伝播で勾配計算')

[-0.45489041 -0.9564946  -0.88816436 -1.39172039  1.43781559  0.02618601
 -1.36314962 -0.45035338  1.11742129 -0.1438435   0.39427343 -0.11989266
  2.6159775   1.46230891  0.95761783 -1.16933029 -0.20177861  0.09269577
 -0.32466426 -0.09327301  0.20172243 -1.04729382  1.23619219 -0.99980235
  1.16062945 -0.71061353 -0.20554088  0.38042898 -0.63874927 -0.93989152
  0.9970509  -1.84328591]
[ 0.77508469  1.55650878 -0.2300693  -0.42972176  0.11870277  0.3241767
  0.06653731 -0.78890168  0.12966413  2.28886016  1.40507886 -1.30862004
  0.39789949 -0.12959832  0.31901971 -0.71346595  0.97313025  0.1731749
 -0.16934535  0.22710528 -1.19979433  0.71139936  1.69064737  0.21953077
 -0.30931978 -0.5769571  -0.23310559  1.38156254  0.14176683 -0.50170908
 -0.27845026 -0.70825373]
[-1.58061347e+00  8.33025295e-01 -1.14564967e+00  3.89753235e-01
  3.38473247e-01  4.10236852e-01 -1.79731218e-01 -2.13081025e-01
  7.65652368e-01 -1.77103632e-01  6.47587505e-01 -1.76338779e-01
 -2.75147159e-01 -5.49675