# 4章コードの補足

In [1]:
import numpy as np
import collections

# コーパスは単語IDのリスト．

counter = collections.Counter()
corpus = np.array([1, 0, 3, 2, 0, 1, 0, 3])

for word_id in corpus:
    counter[word_id] += 1
    
counter

Counter({1: 2, 0: 3, 3: 2, 2: 1})

In [2]:
p = np.zeros(len(counter))
for i in range(len(counter)):
    p[i] = counter[i]

p /= np.sum(p)
p

array([0.375, 0.25 , 0.125, 0.25 ])

In [3]:
samples = np.random.choice(len(counter), size=(20, 5), p=p)

In [4]:
counter = collections.Counter()

for word_id in samples.flatten():
    counter[word_id] += 1

In [5]:
counter

Counter({2: 7, 0: 38, 3: 23, 1: 32})

In [6]:
p = np.zeros(len(counter))
for i in range(len(counter)):
    p[i] = counter[i]

p /= np.sum(p)
p

array([0.38, 0.32, 0.07, 0.23])

[[0.16860902 0.20623086 0.27895794 0.72225706 0.35300136 0.77326383
  0.11842388 0.64773344 0.62032115 0.14783888]
 [0.93365201 0.76590476 0.84562831 0.09192868 0.18766389 0.39580702
  0.48907597 0.85969848 0.11461293 0.75411307]
 [0.61009311 0.14981963 0.90345955 0.20878013 0.23212428 0.82554672
  0.63272929 0.14007513 0.31752882 0.48636024]]
[[0.77326383]
 [0.93365201]
 [0.90345955]]
[[-0.60465481 -0.56703297 -0.49430589 -0.05100677 -0.42026247  0.
  -0.65483995 -0.12553039 -0.15294268 -0.62542495]
 [ 0.         -0.16774725 -0.0880237  -0.84172333 -0.74598813 -0.53784499
  -0.44457605 -0.07395353 -0.81903908 -0.17953894]
 [-0.29336643 -0.75363991  0.         -0.69467941 -0.67133527 -0.07791283
  -0.27073026 -0.76338441 -0.58593073 -0.41709931]]
